// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTHoFf1etJ1fOvItEFXP6ZLH6A465eQy0',
    appId: '1:995866502342:web:0cd8d52badacef6e4ca3c7',
    messagingSenderId: '995866502342',
    projectId: 'restro-44709',
    authDomain: 'restro-44709.firebaseapp.com',
    storageBucket: 'restro-44709.firebasestorage.app',
    measurementId: 'G-7S8D4QV82V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKbTZWs7J_9juuZoCnqtdbKmZes9WgQnA',
    appId: '1:995866502342:android:ddb7933b14ef03554ca3c7',
    messagingSenderId: '995866502342',
    projectId: 'restro-44709',
    storageBucket: 'restro-44709.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHB52O5YEpE7LOvwRMedyyQdpKUi7Ad4E',
    appId: '1:995866502342:ios:d7ab5bbd04e64b6f4ca3c7',
    messagingSenderId: '995866502342',
    projectId: 'restro-44709',
    storageBucket: 'restro-44709.firebasestorage.app',
    iosBundleId: 'com.example.restro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHB52O5YEpE7LOvwRMedyyQdpKUi7Ad4E',
    appId: '1:995866502342:ios:d7ab5bbd04e64b6f4ca3c7',
    messagingSenderId: '995866502342',
    projectId: 'restro-44709',
    storageBucket: 'restro-44709.firebasestorage.app',
    iosBundleId: 'com.example.restro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTHoFf1etJ1fOvItEFXP6ZLH6A465eQy0',
    appId: '1:995866502342:web:138bbc91cf750c944ca3c7',
    messagingSenderId: '995866502342',
    projectId: 'restro-44709',
    authDomain: 'restro-44709.firebaseapp.com',
    storageBucket: 'restro-44709.firebasestorage.app',
    measurementId: 'G-F8CCMR7H6H',
  );
}
